### ISSUE TITLE
Xcode update causing error?

### ISSUE THREAD

**Issue by kimlyndon** [kimlyndon/AnimalSounds#1]
Prior to a recent Xcode update, AnimalSounds was working error-free. After the update, it now shows this error: 

![screen shot 2018-04-11 at 8 45 03 pm](https://user-images.githubusercontent.com/35879608/38772888-12c839f8-400f-11e8-9e5e-982012ddc3c4.png)

I am a newbie and need to understand what these errors mean and how to fix them. I appreciate any assistance!
Thank you

**Comment by bobdel** [comment]
I answered this on Slack but am answering here again because I too need to practice GitHub.

For some reason the target was added as an item in the build phase. Delete that, and those three errors will disappear. The build phase is accessible if you choose the top item in the inspector, then the item underneath Target in the left column. Now, find "Build Phase" across the top. Next find the section "Copy Bundle Resources," highlight and delete the item "AnimalSounds." (See the little minus symbol near the bottom of the list?).

<img width="1280" alt="screen shot 2018-04-22 at 11 52 24 am" src="https://user-images.githubusercontent.com/5385825/39098769-73d8a960-4624-11e8-8dde-11f5c8f01657.png">
